### ISSUE TITLE
After hovering over menu items, the items do not close after hover event

### ISSUE THREAD

**Issue by shubhankar30** [themegrill/suffice#28]
Thank you for making this theme. My issue is that after hovering over the menu items and after removing the hover, the menu closes temporarily but if I move my cursor back in the area where the menu was opened, the menu shows up even though it was closed. 

### Information
- Suffice Theme Version:1.1.2

### Steps to Reproduce:
1. Normal menu.
2. Hover over the menu and hover over some sub menu items
3. Without pressing anything on the menu hover out of the menu
4. Again drag your cursor back to where the menu would have been if it was opened and the menu shows up

Thank you.

**Comment by sethstha** [comment]
Hi, @shubhankar30 

Is it also shows up after few seconds or just after the half second? Transition is set to half second so it might be that you are hovering over on the same area right after it fades away.

I will test this on my side too.
